/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    applicants: ApplicantAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    users: User;
    media: Media;
    applicants: Applicant;
    assessments: Assessment;
    'proctoring-events': ProctoringEvent;
    'proctoring-recordings': ProctoringRecording;
    'proctoring-snapshots': ProctoringSnapshot;
    jobs: Job;
    applications: Application;
    'interview-slots': InterviewSlot;
    resumes: Resume;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    applicants: {
      assessments: 'assessments';
    };
    jobs: {
      applications: 'applications';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    applicants: ApplicantsSelect<false> | ApplicantsSelect<true>;
    assessments: AssessmentsSelect<false> | AssessmentsSelect<true>;
    'proctoring-events': ProctoringEventsSelect<false> | ProctoringEventsSelect<true>;
    'proctoring-recordings': ProctoringRecordingsSelect<false> | ProctoringRecordingsSelect<true>;
    'proctoring-snapshots': ProctoringSnapshotsSelect<false> | ProctoringSnapshotsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    'interview-slots': InterviewSlotsSelect<false> | InterviewSlotsSelect<true>;
    resumes: ResumesSelect<false> | ResumesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    playground: Playground;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    playground: PlaygroundSelect<false> | PlaygroundSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Applicant;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface ApplicantAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Use "home" for the homepage. Other pages are served at /<slug>.
   */
  slug: string;
  layout?: (HeroBlock | FeaturesBlock | ContentStatsBlock | LatestPostsBlock | CallToActionBlock)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Small label shown above the heading.
   */
  eyebrow?: string | null;
  heading: string;
  lead?: string | null;
  buttons?:
    | {
        label: string;
        /**
         * e.g. /about or https://example.com
         */
        url: string;
        newTab?: boolean | null;
        style?: ('primary' | 'outline') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesBlock".
 */
export interface FeaturesBlock {
  /**
   * Small label shown above the heading.
   */
  eyebrow?: string | null;
  heading: string;
  subheading?: string | null;
  items?:
    | {
        title: string;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Section background, from General Settings → Theme.
   */
  background?: ('default' | 'surface') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'features';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentStatsBlock".
 */
export interface ContentStatsBlock {
  /**
   * Small label shown above the heading.
   */
  eyebrow?: string | null;
  heading: string;
  /**
   * Separate paragraphs with a blank line.
   */
  body?: string | null;
  note?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Section background, from General Settings → Theme.
   */
  background?: ('default' | 'surface') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contentStats';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestPostsBlock".
 */
export interface LatestPostsBlock {
  /**
   * Small label shown above the heading.
   */
  eyebrow?: string | null;
  heading: string;
  subheading?: string | null;
  limit: number;
  showViewAll?: boolean | null;
  /**
   * Section background, from General Settings → Theme.
   */
  background?: ('default' | 'surface') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'latestPosts';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  heading: string;
  body?: string | null;
  button?: {
    label?: string | null;
    /**
     * e.g. /about or https://example.com
     */
    url?: string | null;
    newTab?: boolean | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * Short summary shown on blog cards.
   */
  excerpt?: string | null;
  /**
   * Optional. Cards show a themed placeholder when empty.
   */
  coverImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * URL: /blog/<slug>
   */
  slug: string;
  publishedAt: string;
  category?: string | null;
  authorName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Head of Plus users get the hiring emails (booked interviews, finished assessments). If nobody has this role, every admin gets them.
   */
  role?: ('admin' | 'head_of_plus') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Applicants sign up themselves at /applicant/login. Set each one's exam time limit here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applicants".
 */
export interface Applicant {
  id: number;
  name?: string | null;
  /**
   * Used for new exams, and updates any exam they haven't started yet.
   */
  timeLimitMinutes: number;
  /**
   * Whether the applicant has finished signing up.
   */
  passwordSet?: boolean | null;
  assessments?: {
    docs?: (number | Assessment)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'applicants';
}
/**
 * Exam attempts. Applicants get one automatically when they start the exam from their dashboard; you can also create one and send the invite link. Review the submission and set the result.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessments".
 */
export interface Assessment {
  id: number;
  candidateName: string;
  candidateEmail: string;
  /**
   * Shown beside the editor. Leave empty to use the instructions from Settings → Code Playground.
   */
  task?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  durationMinutes: number;
  /**
   * Optional. The Start button appears in My Profile at this time. Set by the hiring workflow.
   */
  availableFrom?: string | null;
  /**
   * Optional. The test can no longer be started after this.
   */
  expiresAt?: string | null;
  /**
   * Records the candidate's webcam in 1-minute clips (Proctoring tab).
   */
  requireWebcam?: boolean | null;
  /**
   * The candidate must share their entire screen, which is recorded in 1-minute clips.
   */
  recordScreen?: boolean | null;
  languageLabel?: string | null;
  languageId?: number | null;
  /**
   * Autosaved while the candidate works; final once submitted.
   */
  code?: string | null;
  /**
   * The server re-runs the submitted code on Judge0 with the candidate's last input, so this output is verified.
   */
  finalRun?: {
    status?: string | null;
    time?: string | null;
    memory?: number | null;
    stdin?: string | null;
    stdout?: string | null;
    errors?: string | null;
  };
  /**
   * Optional. Shown on the applicant's dashboard once a result is set.
   */
  feedback?: string | null;
  /**
   * Shown on the applicant's dashboard.
   */
  result: 'pending' | 'passed' | 'failed';
  applicant?: (number | null) | Applicant;
  /**
   * Use "Reset assessment" above to let the candidate retake the test.
   */
  status: 'invited' | 'in_progress' | 'completed';
  token?: string | null;
  startedAt?: string | null;
  completedAt?: string | null;
  endedBy?: ('submitted' | 'time_expired') | null;
  /**
   * Submitted after the time limit.
   */
  submittedLate?: boolean | null;
  tabSwitches?: number | null;
  timeAwaySeconds?: number | null;
  fullscreenExits?: number | null;
  pastes?: number | null;
  pastedCharacters?: number | null;
  codeRuns?: number | null;
  multipleMonitors?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proctoring-events".
 */
export interface ProctoringEvent {
  id: number;
  assessment: number | Assessment;
  type:
    | 'started'
    | 'resumed'
    | 'left_tab'
    | 'lost_focus'
    | 'fullscreen_exit'
    | 'paste'
    | 'camera_off'
    | 'screen_share_stopped'
    | 'multiple_monitors'
    | 'code_run'
    | 'time_expired'
    | 'submitted';
  at: string;
  durationSeconds?: number | null;
  characters?: number | null;
  detail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Recordings are deleted automatically after 30 days.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proctoring-recordings".
 */
export interface ProctoringRecording {
  id: number;
  assessment: number | Assessment;
  source?: ('webcam' | 'screen') | null;
  startedAt: string;
  endedAt: string;
  durationSeconds?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Older webcam snapshots. Deleted automatically after 30 days.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proctoring-snapshots".
 */
export interface ProctoringSnapshot {
  id: number;
  assessment: number | Assessment;
  takenAt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Open postings are listed at /careers, where candidates apply with their resume.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  title: string;
  /**
   * Used in the URL. Generated from the title.
   */
  slug?: string | null;
  status: 'open' | 'closed';
  location?: string | null;
  employmentType?: string | null;
  /**
   * A short description shown on the careers page.
   */
  summary?: string | null;
  /**
   * One per line. The AI review checks the resume against each of these.
   */
  qualifications: string;
  requiredSkills: {
    skill: string;
    id?: string | null;
  }[];
  /**
   * Candidates at or above this score are invited to book an initial interview.
   */
  minimumScore: number;
  applications?: {
    docs?: (number | Application)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Candidates who applied at /careers. Work through each step in the tabs: AI review, initial interview, technical assessment, final interview.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  email: string;
  name?: string | null;
  job: number | Job;
  resume: number | Resume;
  aiScore?: number | null;
  /**
   * Set automatically from the job's minimum score. Tick it to invite a candidate anyway; this emails them the booking link.
   */
  shortlisted?: boolean | null;
  aiSummary?: string | null;
  aiStrengths?: string | null;
  aiGaps?: string | null;
  aiError?: string | null;
  initialInterviewSlot?: (number | null) | InterviewSlot;
  initialInterviewAt?: string | null;
  initialResult?: ('pending' | 'passed' | 'failed') | null;
  initialNotes?: string | null;
  technicalAssessmentAt?: string | null;
  /**
   * Created automatically. Open it to review the code, recordings and activity.
   */
  assessment?: (number | null) | Assessment;
  /**
   * Same as the Result on the assessment; changing either updates both.
   */
  technicalResult?: ('pending' | 'passed' | 'failed') | null;
  /**
   * Saving emails the candidate this schedule.
   */
  finalInterviewAt?: string | null;
  /**
   * Optional, e.g. the meeting link or address. Included in the email.
   */
  finalInterviewDetails?: string | null;
  /**
   * Updated automatically from the steps below.
   */
  stage?:
    | (
        | 'screening'
        | 'ai_error'
        | 'not_shortlisted'
        | 'invited_to_schedule'
        | 'initial_scheduled'
        | 'initial_failed'
        | 'initial_passed'
        | 'assessment_scheduled'
        | 'assessment_in_progress'
        | 'assessment_submitted'
        | 'assessment_failed'
        | 'assessment_passed'
        | 'final_scheduled'
      )
    | null;
  applicant?: (number | null) | Applicant;
  aiStatus?: ('pending' | 'done' | 'error') | null;
  aiReviewedAt?: string | null;
  assessmentStatus?: string | null;
  schedulingToken?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resumes".
 */
export interface Resume {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Initial interview times candidates can book. A slot is taken once a candidate books it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interview-slots".
 */
export interface InterviewSlot {
  id: number;
  startsAt: string;
  durationMinutes: number;
  /**
   * Optional. Defaults to whoever is Head of Plus.
   */
  interviewer?: (number | null) | User;
  /**
   * Optional. Sent to the candidate when they book.
   */
  meetingLink?: string | null;
  /**
   * Filled in when a candidate books this slot. Clear it to free the slot.
   */
  application?: (number | null) | Application;
  label?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'applicants';
        value: number | Applicant;
      } | null)
    | ({
        relationTo: 'assessments';
        value: number | Assessment;
      } | null)
    | ({
        relationTo: 'proctoring-events';
        value: number | ProctoringEvent;
      } | null)
    | ({
        relationTo: 'proctoring-recordings';
        value: number | ProctoringRecording;
      } | null)
    | ({
        relationTo: 'proctoring-snapshots';
        value: number | ProctoringSnapshot;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'interview-slots';
        value: number | InterviewSlot;
      } | null)
    | ({
        relationTo: 'resumes';
        value: number | Resume;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'applicants';
        value: number | Applicant;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'applicants';
        value: number | Applicant;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        features?: T | FeaturesBlockSelect<T>;
        contentStats?: T | ContentStatsBlockSelect<T>;
        latestPosts?: T | LatestPostsBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  lead?: T;
  buttons?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        style?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturesBlock_select".
 */
export interface FeaturesBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  items?:
    | T
    | {
        title?: T;
        body?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentStatsBlock_select".
 */
export interface ContentStatsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  body?: T;
  note?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LatestPostsBlock_select".
 */
export interface LatestPostsBlockSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  limit?: T;
  showViewAll?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  button?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  coverImage?: T;
  content?: T;
  slug?: T;
  publishedAt?: T;
  category?: T;
  authorName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applicants_select".
 */
export interface ApplicantsSelect<T extends boolean = true> {
  name?: T;
  timeLimitMinutes?: T;
  passwordSet?: T;
  assessments?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "assessments_select".
 */
export interface AssessmentsSelect<T extends boolean = true> {
  candidateName?: T;
  candidateEmail?: T;
  task?: T;
  durationMinutes?: T;
  availableFrom?: T;
  expiresAt?: T;
  requireWebcam?: T;
  recordScreen?: T;
  languageLabel?: T;
  languageId?: T;
  code?: T;
  finalRun?:
    | T
    | {
        status?: T;
        time?: T;
        memory?: T;
        stdin?: T;
        stdout?: T;
        errors?: T;
      };
  feedback?: T;
  result?: T;
  applicant?: T;
  status?: T;
  token?: T;
  startedAt?: T;
  completedAt?: T;
  endedBy?: T;
  submittedLate?: T;
  tabSwitches?: T;
  timeAwaySeconds?: T;
  fullscreenExits?: T;
  pastes?: T;
  pastedCharacters?: T;
  codeRuns?: T;
  multipleMonitors?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proctoring-events_select".
 */
export interface ProctoringEventsSelect<T extends boolean = true> {
  assessment?: T;
  type?: T;
  at?: T;
  durationSeconds?: T;
  characters?: T;
  detail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proctoring-recordings_select".
 */
export interface ProctoringRecordingsSelect<T extends boolean = true> {
  assessment?: T;
  source?: T;
  startedAt?: T;
  endedAt?: T;
  durationSeconds?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "proctoring-snapshots_select".
 */
export interface ProctoringSnapshotsSelect<T extends boolean = true> {
  assessment?: T;
  takenAt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  location?: T;
  employmentType?: T;
  summary?: T;
  qualifications?: T;
  requiredSkills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  minimumScore?: T;
  applications?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  job?: T;
  resume?: T;
  aiScore?: T;
  shortlisted?: T;
  aiSummary?: T;
  aiStrengths?: T;
  aiGaps?: T;
  aiError?: T;
  initialInterviewSlot?: T;
  initialInterviewAt?: T;
  initialResult?: T;
  initialNotes?: T;
  technicalAssessmentAt?: T;
  assessment?: T;
  technicalResult?: T;
  finalInterviewAt?: T;
  finalInterviewDetails?: T;
  stage?: T;
  applicant?: T;
  aiStatus?: T;
  aiReviewedAt?: T;
  assessmentStatus?: T;
  schedulingToken?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "interview-slots_select".
 */
export interface InterviewSlotsSelect<T extends boolean = true> {
  startsAt?: T;
  durationMinutes?: T;
  interviewer?: T;
  meetingLink?: T;
  application?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resumes_select".
 */
export interface ResumesSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  theme?: {
    /**
     * Used for h1–h6.
     */
    headingFont?:
      | (
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'poppins'
          | 'dm-sans'
          | 'space-grotesk'
          | 'playfair-display'
          | 'merriweather'
          | 'lora'
          | 'source-serif-4'
          | 'system'
        )
      | null;
    /**
     * Used for paragraphs, sub paragraphs and UI text.
     */
    bodyFont?:
      | (
          | 'inter'
          | 'roboto'
          | 'open-sans'
          | 'lato'
          | 'montserrat'
          | 'poppins'
          | 'dm-sans'
          | 'space-grotesk'
          | 'playfair-display'
          | 'merriweather'
          | 'lora'
          | 'source-serif-4'
          | 'system'
        )
      | null;
    headingColor?: string | null;
    paragraphColor?: string | null;
    /**
     * Taglines, captions and secondary text.
     */
    subParagraphColor?: string | null;
    /**
     * Buttons, links and accents.
     */
    primaryColor?: string | null;
    backgroundColor?: string | null;
    /**
     * Cards and alternate sections.
     */
    surfaceColor?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        label: string;
        /**
         * e.g. /about or https://example.com
         */
        url: string;
        newTab?: boolean | null;
        children?:
          | {
              label: string;
              /**
               * e.g. /about or https://example.com
               */
              url: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        heading?: string | null;
        links?:
          | {
              label: string;
              /**
               * e.g. /about or https://example.com
               */
              url: string;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * e.g. © 2026 My Company. All rights reserved.
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Instructions shown beside the code editor at /playground.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playground".
 */
export interface Playground {
  id: number;
  heading: string;
  /**
   * The task for the user, e.g. the problem statement, input format and rules.
   */
  instructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  theme?:
    | T
    | {
        headingFont?: T;
        bodyFont?: T;
        headingColor?: T;
        paragraphColor?: T;
        subParagraphColor?: T;
        primaryColor?: T;
        backgroundColor?: T;
        surfaceColor?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "playground_select".
 */
export interface PlaygroundSelect<T extends boolean = true> {
  heading?: T;
  instructions?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}